name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
      with: 
        repository: anton1eonenko/https://github.com/anton1eonenko/SAPsb_automationTesting_template_playwright

    - name: Checkout main repo
      uses: actions/checkout@v2
      with: 
        repository: anto1eonenko/https://github.com/anton1eonenko/SAPcpq_automationTesting_template_playwright

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: 
        cd anton1eonenko/https://github.com/anton1eonenko/SAPcpq_automationTesting_template_playwright
        npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run:
        cd anton1eonenko/https://github.com/anton1eonenko/SAPcpq_automationTesting_template_playwright
        npx playwright test


    - name: Generate Allure report
      run: |
        npm install -g allure-commandline
        allure generate --clean -o allure-report

    - name: Archive Allure report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: allure-report
        path: | 
          allure-results/
          allure-report/
        retention-days: 30
